# Generated by Django 4.1.1 on 2022-10-30 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="booking",
            name="is_occupied",
            field=models.BooleanField(default=False),
        ),
    ]
