# Generated by Django 4.1.1 on 2022-10-10 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_remove_customer_has_occupied"),
    ]

    operations = [
        migrations.AddField(
            model_name="customer",
            name="has_occupied",
            field=models.BooleanField(default=False),
        ),
    ]
