# Generated by Django 4.1.1 on 2022-10-10 06:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_customer_has_occupied"),
    ]

    operations = [
        migrations.AlterField(
            model_name="response",
            name="date_time",
            field=models.DateTimeField(
                default=datetime.datetime(2022, 10, 10, 12, 13, 5, 266097)
            ),
        ),
    ]
