# Generated by Django 4.1.1 on 2022-10-10 14:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_alter_response_date_time"),
    ]

    operations = [
        migrations.AlterField(
            model_name="feedback",
            name="date_time",
            field=models.DateTimeField(
                default=datetime.datetime(2022, 10, 10, 19, 52, 8, 85904)
            ),
        ),
        migrations.AlterField(
            model_name="response",
            name="date_time",
            field=models.DateTimeField(
                default=datetime.datetime(2022, 10, 10, 19, 52, 8, 85904)
            ),
        ),
    ]
