# Generated by Django 4.1.1 on 2022-10-14 11:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0005_alter_feedback_date_time_alter_response_date_time"),
    ]

    operations = [
        migrations.AddField(
            model_name="booking",
            name="amount",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="feedback",
            name="date_time",
            field=models.DateTimeField(
                default=datetime.datetime(2022, 10, 14, 17, 26, 47, 818261)
            ),
        ),
        migrations.AlterField(
            model_name="response",
            name="date_time",
            field=models.DateTimeField(
                default=datetime.datetime(2022, 10, 14, 17, 26, 47, 819260)
            ),
        ),
    ]
