# Generated by Django 4.1.2 on 2022-10-23 08:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_booking_amount_alter_feedback_date_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='date_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 23, 14, 19, 28, 814471)),
        ),
        migrations.AlterField(
            model_name='response',
            name='date_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 23, 14, 19, 28, 814471)),
        ),
    ]
